// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Slicito.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "Slicito.VisualStudio.e85dcab9-29e0-4e2e-8168-7e1550afb6c4";
        public const string Name = "Slicito.VisualStudio";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Robert Husák";
        public const string Tags = "";
    }
}
