// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Slicito.VisualStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "Slicito.e85dcab9-29e0-4e2e-8168-7e1550afb6c4";
        public const string Name = "Slicito";
        public const string Description = @"Slicito enables you to analyze your C# code and create interactive visualizations from it.";
        public const string Language = "en-US";
        public const string Version = "0.3.0";
        public const string Author = "Robert Husak";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
